import EventsDispatcher from '../EventsDispatcher';
import { IRunner, ITransport } from '../Transport';
import Connection from './Connection';
import { ISFSocketConfig } from '../SFSocket';
import { IConnectionCallbacks, IErrorCallbacks } from './types';
export default class ConnectionManager extends EventsDispatcher {
    options: ISFSocketConfig;
    state: string;
    connection: Connection | null;
    usingTLS: boolean;
    unavailableTimer: number;
    retryTimer: number;
    transport: ITransport;
    runner: IRunner | null;
    errorCallbacks: IErrorCallbacks;
    connectionCallbacks: IConnectionCallbacks;
    constructor(options: ISFSocketConfig);
    connect(): void;
    send(data: string): boolean;
    sendEvent(name: string, data: string[], channel?: string): boolean;
    disconnect(): void;
    private startConnecting;
    private abortConnecting;
    private disconnectInternally;
    private retryIn;
    private clearRetryTimer;
    private setUnavailableTimer;
    private clearUnavailableTimer;
    private buildConnectionCallbacks;
    private buildErrorCallbacks;
    private setConnection;
    private abandonConnection;
    private updateState;
    private shouldRetry;
}
